// football-data.org TLA → { flag: flagcdn ISO2, name: español }
const MAP = {
  // CONMEBOL
  ARG: { flag: 'ar', name: 'Argentina' },
  BRA: { flag: 'br', name: 'Brasil' },
  COL: { flag: 'co', name: 'Colombia' },
  ECU: { flag: 'ec', name: 'Ecuador' },
  URU: { flag: 'uy', name: 'Uruguay' },
  VEN: { flag: 've', name: 'Venezuela' },
  CHI: { flag: 'cl', name: 'Chile' },
  PAR: { flag: 'py', name: 'Paraguay' },
  PER: { flag: 'pe', name: 'Perú' },
  BOL: { flag: 'bo', name: 'Bolivia' },
  // CONCACAF
  USA: { flag: 'us', name: 'USA' },
  CAN: { flag: 'ca', name: 'Canadá' },
  MEX: { flag: 'mx', name: 'México' },
  PAN: { flag: 'pa', name: 'Panamá' },
  CRC: { flag: 'cr', name: 'Costa Rica' },
  HON: { flag: 'hn', name: 'Honduras' },
  JAM: { flag: 'jm', name: 'Jamaica' },
  HTI: { flag: 'ht', name: 'Haití' },
  SUR: { flag: 'sr', name: 'Surinam' },
  TRI: { flag: 'tt', name: 'Trinidad y Tobago' },
  // UEFA
  ESP: { flag: 'es', name: 'España' },
  FRA: { flag: 'fr', name: 'Francia' },
  GER: { flag: 'de', name: 'Alemania' },
  ENG: { flag: 'gb-eng', name: 'Inglaterra' },
  ITA: { flag: 'it', name: 'Italia' },
  POR: { flag: 'pt', name: 'Portugal' },
  NED: { flag: 'nl', name: 'Países Bajos' },
  BEL: { flag: 'be', name: 'Bélgica' },
  SUI: { flag: 'ch', name: 'Suiza' },
  AUT: { flag: 'at', name: 'Austria' },
  DEN: { flag: 'dk', name: 'Dinamarca' },
  CRO: { flag: 'hr', name: 'Croacia' },
  SRB: { flag: 'rs', name: 'Serbia' },
  SCO: { flag: 'gb-sct', name: 'Escocia' },
  CZE: { flag: 'cz', name: 'Chequia' },
  POL: { flag: 'pl', name: 'Polonia' },
  TUR: { flag: 'tr', name: 'Turquía' },
  HUN: { flag: 'hu', name: 'Hungría' },
  NOR: { flag: 'no', name: 'Noruega' },
  WAL: { flag: 'gb-wls', name: 'Gales' },
  UKR: { flag: 'ua', name: 'Ucrania' },
  SVK: { flag: 'sk', name: 'Eslovaquia' },
  SVN: { flag: 'si', name: 'Eslovenia' },
  ROU: { flag: 'ro', name: 'Rumanía' },
  ALB: { flag: 'al', name: 'Albania' },
  GRE: { flag: 'gr', name: 'Grecia' },
  ISL: { flag: 'is', name: 'Islandia' },
  FIN: { flag: 'fi', name: 'Finlandia' },
  IRL: { flag: 'ie', name: 'Irlanda' },
  // CAF
  MAR: { flag: 'ma', name: 'Marruecos' },
  SEN: { flag: 'sn', name: 'Senegal' },
  NGA: { flag: 'ng', name: 'Nigeria' },
  CIV: { flag: 'ci', name: 'Costa de Marfil' },
  EGY: { flag: 'eg', name: 'Egipto' },
  TUN: { flag: 'tn', name: 'Túnez' },
  GHA: { flag: 'gh', name: 'Ghana' },
  CMR: { flag: 'cm', name: 'Camerún' },
  RSA: { flag: 'za', name: 'Sudáfrica' },
  MLI: { flag: 'ml', name: 'Mali' },
  COD: { flag: 'cd', name: 'DR Congo' },
  ALG: { flag: 'dz', name: 'Argelia' },
  GUI: { flag: 'gn', name: 'Guinea' },
  ZIM: { flag: 'zw', name: 'Zimbabue' },
  UGA: { flag: 'ug', name: 'Uganda' },
  // AFC
  JPN: { flag: 'jp', name: 'Japón' },
  KOR: { flag: 'kr', name: 'Corea del Sur' },
  IRN: { flag: 'ir', name: 'Irán' },
  AUS: { flag: 'au', name: 'Australia' },
  KSA: { flag: 'sa', name: 'Arabia Saudí' },
  SAU: { flag: 'sa', name: 'Arabia Saudí' },
  QAT: { flag: 'qa', name: 'Catar' },
  UZB: { flag: 'uz', name: 'Uzbekistán' },
  JOR: { flag: 'jo', name: 'Jordania' },
  IRQ: { flag: 'iq', name: 'Irak' },
  OMN: { flag: 'om', name: 'Omán' },
  THA: { flag: 'th', name: 'Tailandia' },
  CHN: { flag: 'cn', name: 'China' },
  // OFC
  NZL: { flag: 'nz', name: 'Nueva Zelanda' },
  // AFC extras
  KAZ: { flag: 'kz', name: 'Kazajistán' },
  BHR: { flag: 'bh', name: 'Baréin' },
  PHI: { flag: 'ph', name: 'Filipinas' },
  IDN: { flag: 'id', name: 'Indonesia' },
  KGZ: { flag: 'kg', name: 'Kirguistán' },
  TJK: { flag: 'tj', name: 'Tayikistán' },
  VIE: { flag: 'vn', name: 'Vietnam' },
  MYA: { flag: 'mm', name: 'Myanmar' },
  HKG: { flag: 'hk', name: 'Hong Kong' },
  TPE: { flag: 'tw', name: 'Taiwán' },
  MAC: { flag: 'mo', name: 'Macao' },
  // CAF extras
  CPV: { flag: 'cv', name: 'Cabo Verde' },
  MOZ: { flag: 'mz', name: 'Mozambique' },
  TAN: { flag: 'tz', name: 'Tanzania' },
  KEN: { flag: 'ke', name: 'Kenia' },
  NAM: { flag: 'na', name: 'Namibia' },
  ANG: { flag: 'ao', name: 'Angola' },
  ETH: { flag: 'et', name: 'Etiopía' },
  COM: { flag: 'km', name: 'Comoras' },
  BEN: { flag: 'bj', name: 'Benín' },
  BFA: { flag: 'bf', name: 'Burkina Faso' },
  TOG: { flag: 'tg', name: 'Togo' },
  NIG: { flag: 'ne', name: 'Níger' },
  GAM: { flag: 'gm', name: 'Gambia' },
  MTN: { flag: 'mr', name: 'Mauritania' },
  LBR: { flag: 'lr', name: 'Liberia' },
  SLE: { flag: 'sl', name: 'Sierra Leona' },
  GNB: { flag: 'gw', name: 'Guinea-Bisáu' },
  CGO: { flag: 'cg', name: 'Congo' },
  ZAM: { flag: 'zm', name: 'Zambia' },
  RWA: { flag: 'rw', name: 'Ruanda' },
  GAB: { flag: 'ga', name: 'Gabón' },
  EQG: { flag: 'gq', name: 'Guinea Ecuatorial' },
  SOM: { flag: 'so', name: 'Somalia' },
  SDN: { flag: 'sd', name: 'Sudán' },
  LBA: { flag: 'ly', name: 'Libia' },
  // CONCACAF extras
  CUB: { flag: 'cu', name: 'Cuba' },
  GUA: { flag: 'gt', name: 'Guatemala' },
  SLV: { flag: 'sv', name: 'El Salvador' },
  NCA: { flag: 'ni', name: 'Nicaragua' },
  CUW: { flag: 'cw', name: 'Curazao' },
  BLZ: { flag: 'bz', name: 'Belice' },
  // UEFA extras
  BIH: { flag: 'ba', name: 'Bosnia y Herz.' },
  MNE: { flag: 'me', name: 'Montenegro' },
  MKD: { flag: 'mk', name: 'Macedonia del Norte' },
  BLR: { flag: 'by', name: 'Bielorrusia' },
  GEO: { flag: 'ge', name: 'Georgia' },
  ARM: { flag: 'am', name: 'Armenia' },
  AZE: { flag: 'az', name: 'Azerbaiyán' },
  LUX: { flag: 'lu', name: 'Luxemburgo' },
  KOS: { flag: 'xk', name: 'Kosovo' },
  // CONMEBOL extras
  GUY: { flag: 'gy', name: 'Guyana' },
}

export function getTeamInfo(tla) {
  if (!tla) return { flag: 'un', name: 'Por definir' }
  const info = MAP[tla]
  if (!info) console.warn(`[teamMappings] TLA no mapeado: ${tla}`)
  return info ?? { flag: tla.slice(0, 2).toLowerCase(), name: tla }
}
